// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suyaaextkifjxjuvqbqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1eWFhZXh0a2lmanhqdXZxYnF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzY5OTYsImV4cCI6MjA3MTgxMjk5Nn0.SOz1qtrDtuEQvAR3ovlwkKWk05XprrUUsx_Qd1NyWYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});